# Hand made .travis.yml from pkg/travis.yml

language: perl

perl:
- '5.20'
- '5.18'
- '5.16'
- '5.14'
- '5.12'
- '5.10'
- '5.8'

install:
- cpanm --quiet --notest
  Devel::Cover::Report::Coveralls
  Test::Base
  Zilla::Dist
- git clone https://github.com/ingydotnet/test-base-pm
  ../test-base-pm

script:
- zild disttest
- cover

after_success:
- cover -report coveralls

notifications:
  irc:
    channels:
    - irc.perl.org#yaml
    on_success: change
    on_failure: always
    skip_join: true

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
